# Generated by Django 5.2.8 on 2026-03-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subscription_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconfiguration',
            options={'ordering': ['service_type'], 'verbose_name': 'Configuration de Service', 'verbose_name_plural': 'Configurations'},
        ),
    ]
