"""
Django settings for Christlumen project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta
from urllib.parse import urlparse
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the backend-local .env file first.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

def _split_env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def _host_from_url(url):
    if not url:
        return ""
    try:
        return urlparse(url).hostname or ""
    except ValueError:
        return ""


ALLOWED_HOSTS = _split_env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
if DEBUG:
    for host in ("localhost", "127.0.0.1"):
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

# Frontend and API URLs from environment
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')
API_URL = os.getenv('API_URL', 'http://localhost:8000')
WS_URL = os.getenv('WS_URL', 'ws://localhost:8000')

for host in (_host_from_url(FRONTEND_URL), _host_from_url(API_URL), _host_from_url(WS_URL)):
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Application definition

INSTALLED_APPS = [
    # 'daphne',  # Optional: for production ASGI server
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'channels',
    "api"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS - must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.MaintenanceModeMiddleware',  # Maintenance mode middleware
]

ROOT_URLCONF = 'christlumen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'christlumen.wsgi.application'
ASGI_APPLICATION = 'christlumen.asgi.application'

# Channels configuration
CHANNEL_LAYER_BACKEND = os.getenv("CHANNEL_LAYER_BACKEND", "memory").lower()
if CHANNEL_LAYER_BACKEND == "redis":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3'), conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "api.User"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
META_PHONE_ID = os.getenv("META_PHONE_ID")
META_WHATSAPP_API_KEY = os.getenv("META_WHATSAPP_API_KEY")
OTP_EXPIRATION_SECONDS = int(os.getenv("OTP_EXPIRATION_SECONDS", 300))
OTP_SEND_COOLDOWN_SECONDS = int(os.getenv("OTP_SEND_COOLDOWN_SECONDS", 60))
META_WA_TOKEN=os.getenv("META_WA_TOKEN")
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Maintenance Mode Configuration
MAINTENANCE_MODE = os.getenv('MAINTENANCE_MODE', 'False').lower() == 'true'
MAINTENANCE_MESSAGE = os.getenv('MAINTENANCE_MESSAGE', 'Application en maintenance. Veuillez réessayer plus tard.')

# Nexaah SMS API Configuration
NEXAAH_SMS_ENABLED = os.getenv('NEXAAH_SMS_ENABLED', 'False').lower() == 'true'
NEXAAH_BASE_URL = os.getenv('NEXAAH_BASE_URL', 'https://api.nexaah.net')
NEXAAH_SEND_ENDPOINT = os.getenv('NEXAAH_SEND_ENDPOINT', '/send')
NEXAAH_CREDITS_ENDPOINT = os.getenv('NEXAAH_CREDITS_ENDPOINT', '/credits')
NEXAAH_USER = os.getenv('NEXAAH_USER', '')
NEXAAH_PASSWORD = os.getenv('NEXAAH_PASSWORD', '')
NEXAAH_SENDER_ID = os.getenv('NEXAAH_SENDER_ID', 'Christlumen')

# WhatsApp API Configuration
WHATSAPP_ENABLED = os.getenv('WHATSAPP_ENABLED', 'False').lower() == 'true'
WHATSAPP_API_TOKEN = os.getenv('WHATSAPP_API_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_API_VERSION = os.getenv('WHATSAPP_API_VERSION', 'v18.0')
WHATSAPP_TEMPLATE_NAME = os.getenv('WHATSAPP_TEMPLATE_NAME', '')
WHATSAPP_OTP_TEMPLATE_NAME = os.getenv('WHATSAPP_OTP_TEMPLATE_NAME', '')
WHATSAPP_LANGUAGE = os.getenv('WHATSAPP_LANGUAGE', 'fr')

# Email Configuration
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@christlumen.local')
OTP_EMAIL_SUBJECT = os.getenv(
    'OTP_EMAIL_SUBJECT',
    'Votre code OTP Christlumen',
)

# FreeMoPay API Configuration
FREEMOPAY_ENABLED = os.getenv('FREEMOPAY_ENABLED', 'False').lower() == 'true'
FREEMOPAY_BASE_URL = os.getenv('FREEMOPAY_BASE_URL', 'https://api.freemopay.com')
FREEMOPAY_APP_KEY = os.getenv('FREEMOPAY_APP_KEY', '')
FREEMOPAY_SECRET_KEY = os.getenv('FREEMOPAY_SECRET_KEY', '')
FREEMOPAY_CALLBACK_URL = os.getenv('FREEMOPAY_CALLBACK_URL', f'{API_URL}/api/payments/freemopay/callback')
FREEMOPAY_INIT_PAYMENT_TIMEOUT = int(os.getenv('FREEMOPAY_INIT_PAYMENT_TIMEOUT', '60'))
FREEMOPAY_STATUS_CHECK_TIMEOUT = int(os.getenv('FREEMOPAY_STATUS_CHECK_TIMEOUT', '30'))
FREEMOPAY_TOKEN_TIMEOUT = int(os.getenv('FREEMOPAY_TOKEN_TIMEOUT', '60'))
FREEMOPAY_TOKEN_CACHE_DURATION = int(os.getenv('FREEMOPAY_TOKEN_CACHE_DURATION', '3600'))
FREEMOPAY_MAX_RETRIES = int(os.getenv('FREEMOPAY_MAX_RETRIES', '3'))
FREEMOPAY_RETRY_DELAY = float(os.getenv('FREEMOPAY_RETRY_DELAY', '1.0'))

# Notification Preferences
DEFAULT_NOTIFICATION_CHANNEL = os.getenv('DEFAULT_NOTIFICATION_CHANNEL', 'whatsapp')

#Token
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
}
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Christlumen API",
    "DESCRIPTION": "API REST pour la plateforme Christlumen - Gestion d'églises, contenus, événements, dons et commandes",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    "SECURITY": [{"Bearer": []}],
    "SERVERS": [
        {"url": "http://localhost:8000", "description": "Serveur de développement"},
        {"url": "https://api.christlumen.com", "description": "Serveur de production"},
    ],
}

# Jazzmin settings - Modern Christlumen Design
JAZZMIN_SETTINGS = {
    # Title
    "site_title": "Christlumen Admin",
    "site_header": "Christlumen",
    "site_brand": "Christlumen",
    "site_logo": "admin/img/christlumen-logo.jpeg",  # Logo path
    "login_logo": "admin/img/christlumen-logo.jpeg",
    "site_logo_classes": "img-fluid",
    "site_icon": "admin/img/christlumen-icon.jpeg",

    # Welcome text
    "welcome_sign": "Bienvenue sur Christlumen - La lumière du Christ",

    # Copyright
    "copyright": "Christlumen © 2024 - Tous droits réservés",

    # Search model
    "search_model": ["api.User", "api.Church", "api.Content", "api.Donation", "api.Programme"],

    # Top Menu
    "topmenu_links": [
        {"name": "Tableau", "url": "admin:index", "permissions": ["auth.view_user"], "icon": "fas fa-home"},
        {"name": "APIs", "url": "/api/docs/", "new_window": True, "icon": "fas fa-book"},
        {"name": "Site", "url": "/", "new_window": True, "icon": "fas fa-globe"},
    ],

    # User Menu
    "usermenu_links": [
        {"name": "Mon profil", "url": "admin:password_change", "icon": "fas fa-user-circle"},
        {"model": "api.user"},
    ],

    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["api", "auth"],

    # Icons - Modern & Elegant
    "icons": {
        "api": "fas fa-layer-group",
        "api.user": "fas fa-users",
        "api.church": "fas fa-church",
        "api.content": "fas fa-file-alt",
        "api.donation": "fas fa-donate",
        "api.donationcategory": "fas fa-list-ul",
        "api.bookorder": "fas fa-shopping-bag",
        "api.testimony": "fas fa-comments",
        "api.payment": "fas fa-credit-card",
        "api.programme": "fas fa-calendar-alt",
        "api.ticket": "fas fa-ticket-alt",
        "api.tickettype": "fas fa-tags",
        "api.ticketreservation": "fas fa-clock",
        "api.churchcollaboration": "fas fa-handshake",
        "api.churchadmin": "fas fa-user-shield",
        "api.subscription": "fas fa-crown",
        "api.subscriptionplan": "fas fa-gem",
        "api.notification": "fas fa-bell",
        "api.otp": "fas fa-key",
        "api.category": "fas fa-folder",
        "api.serviceconfiguration": "fas fa-cogs",
        "auth": "fas fa-shield-alt",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users-cog",
    },

    # Default icons
    "default_icon_parents": "fas fa-angle-right",
    "default_icon_children": "fas fa-dot-circle",

    # Related modal
    "related_modal_active": True,

    # Custom CSS/JS
    "custom_css": "admin/css/christlumen-custom.css",
    "custom_js": None,

    # Show/Hide
    "show_ui_builder": False,

    # Change form
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "api.user": "vertical_tabs",
        "api.church": "horizontal_tabs",
        "api.content": "horizontal_tabs",
        "api.donation": "collapsible",
    },

    # Language
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "darkly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-outline-light",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _split_env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000",
)
if FRONTEND_URL and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
